# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Server

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PingResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPingResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PingResponse()
        x.Init(buf, n + offset)
        return x

    # PingResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PingResponse
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def PingResponseStart(builder): builder.StartObject(1)
def PingResponseAddTimestamp(builder, timestamp): builder.PrependInt64Slot(0, timestamp, 0)
def PingResponseEnd(builder): return builder.EndObject()
