# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Server

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PingRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPingRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PingRequest()
        x.Init(buf, n + offset)
        return x

    # PingRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PingRequestStart(builder): builder.StartObject(0)
def PingRequestEnd(builder): return builder.EndObject()
