from enum import IntEnum

VALID_SUFFIXES = ('jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'heic', 'mov', 'mp4', 'mpeg', 'mpg', 'm4v', 'avi', 'pdf', 'nef', 'vob')

READ_CHUNK_SIZE = 1024 * 1024

LARGE_NUMBER_OF_CHILDREN = 20000

CACHE_LOAD_TIMEOUT_SEC = 30

OBJ_TYPE_LOCAL_DISK = 1
OBJ_TYPE_GDRIVE = 2
OBJ_TYPE_MIXED = 3
OBJ_TYPE_DISPLAY_ONLY = 4

MAIN_REGISTRY_FILE_NAME = 'registry.db'
ROOT_PATH = '/'
ROOT_UID = 1
NULL_UID = 0
GDRIVE_PATH_PREFIX = 'gdrive:/'

GDRIVE_CLIENT_REQUEST_MAX_RETRIES = 10

PROGRESS_BAR_SLEEP_TIME_SEC = 0.5
PROGRESS_BAR_PULSE_STEP = 0.5
PROGRESS_BAR_MAX_MSG_LENGTH = 80

ICON_GENERIC_FILE = 'file'
ICON_TRASHED_DIR = 'trash-dir'
ICON_TRASHED_FILE = 'trash-file'
ICON_GENERIC_DIR = 'folder'
ICON_ADD_DIR = 'add-dir'
ICON_GDRIVE = 'gdrive'
ICON_LOCAL_DISK = 'local'

FILE_META_CHANGE_TOKEN_PROGRESS_AMOUNT = 100  # TODO: put in config

# GDrive
NOT_TRASHED = 0
EXPLICITLY_TRASHED = 1
IMPLICITLY_TRASHED = 2

GDRIVE_DOWNLOAD_TYPE_LOAD_ALL = 1

GDRIVE_DOWNLOAD_STATE_NOT_STARTED = 0
GDRIVE_DOWNLOAD_STATE_GETTING_DIRS = 1
GDRIVE_DOWNLOAD_STATE_GETTING_NON_DIRS = 2
GDRIVE_DOWNLOAD_STATE_READY_TO_COMPILE = 3
GDRIVE_DOWNLOAD_STATE_COMPLETE = 10

TRASHED_STATUS = ['No', 'UserTrashed', 'Trashed']

class TreeDisplayMode(IntEnum):
    ONE_TREE_ALL_ITEMS = 1
    CHANGES_ONE_TREE_PER_CATEGORY = 2

