# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outlet/daemon/grpc/Outlet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from outlet.daemon.grpc import Node_pb2 as outlet_dot_daemon_dot_grpc_dot_Node__pb2

from outlet.daemon.grpc.Node_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='outlet/daemon/grpc/Outlet.proto',
  package='outlet.daemon.grpc',
  syntax='proto3',
  serialized_options=b'\n\023com.msvoboda.outletP\001Z\031msvoboda.com/outlet/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1foutlet/daemon/grpc/Outlet.proto\x12\x12outlet.daemon.grpc\x1a\x1doutlet/daemon/grpc/Node.proto\"\r\n\x0bPingRequest\"!\n\x0cPingResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"E\n\x1dReadSingleNodeFromDiskRequest\x12\x11\n\tfull_path\x18\x01 \x01(\t\x12\x11\n\ttree_type\x18\x02 \x01(\x05\x32\xcb\x01\n\x06Outlet\x12K\n\x04ping\x12\x1f.outlet.daemon.grpc.PingRequest\x1a .outlet.daemon.grpc.PingResponse\"\x00\x12t\n#read_single_node_from_disk_for_path\x12\x31.outlet.daemon.grpc.ReadSingleNodeFromDiskRequest\x1a\x18.outlet.daemon.grpc.Node\"\x00\x42\x32\n\x13\x63om.msvoboda.outletP\x01Z\x19msvoboda.com/outlet/protoP\x00\x62\x06proto3'
  ,
  dependencies=[outlet_dot_daemon_dot_grpc_dot_Node__pb2.DESCRIPTOR,],
  public_dependencies=[outlet_dot_daemon_dot_grpc_dot_Node__pb2.DESCRIPTOR,])




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='outlet.daemon.grpc.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=99,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='outlet.daemon.grpc.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='outlet.daemon.grpc.PingResponse.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=134,
)


_READSINGLENODEFROMDISKREQUEST = _descriptor.Descriptor(
  name='ReadSingleNodeFromDiskRequest',
  full_name='outlet.daemon.grpc.ReadSingleNodeFromDiskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_path', full_name='outlet.daemon.grpc.ReadSingleNodeFromDiskRequest.full_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tree_type', full_name='outlet.daemon.grpc.ReadSingleNodeFromDiskRequest.tree_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['ReadSingleNodeFromDiskRequest'] = _READSINGLENODEFROMDISKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'outlet.daemon.grpc.Outlet_pb2'
  # @@protoc_insertion_point(class_scope:outlet.daemon.grpc.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'outlet.daemon.grpc.Outlet_pb2'
  # @@protoc_insertion_point(class_scope:outlet.daemon.grpc.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

ReadSingleNodeFromDiskRequest = _reflection.GeneratedProtocolMessageType('ReadSingleNodeFromDiskRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSINGLENODEFROMDISKREQUEST,
  '__module__' : 'outlet.daemon.grpc.Outlet_pb2'
  # @@protoc_insertion_point(class_scope:outlet.daemon.grpc.ReadSingleNodeFromDiskRequest)
  })
_sym_db.RegisterMessage(ReadSingleNodeFromDiskRequest)


DESCRIPTOR._options = None

_OUTLET = _descriptor.ServiceDescriptor(
  name='Outlet',
  full_name='outlet.daemon.grpc.Outlet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=411,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='outlet.daemon.grpc.Outlet.ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read_single_node_from_disk_for_path',
    full_name='outlet.daemon.grpc.Outlet.read_single_node_from_disk_for_path',
    index=1,
    containing_service=None,
    input_type=_READSINGLENODEFROMDISKREQUEST,
    output_type=outlet_dot_daemon_dot_grpc_dot_Node__pb2._NODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUTLET)

DESCRIPTOR.services_by_name['Outlet'] = _OUTLET

# @@protoc_insertion_point(module_scope)
